### ISSUE TITLE
Lucide [0.451.0]

### ISSUE THREAD

**Issue by raul-gracia** [Rails-Designer/rails_icons_vault#5]
There seem to be quite a few new icons that has been added:

https://github.com/lucide-icons/lucide/releases/tag/0.451.0

**Comment by raul-gracia** [comment]
@jordancalhoun

**Comment by jordancalhoun** [comment]
Agreed, many are missing.  I will get a PR together with the new icons today so they are working for the time being. 

@eelcoj are you open to the idea of moving the syncing function of the rails_icon gem to pull the files directly from their repo or is there a specific reason you decided to move them into this vault repo?  I can implement the change on the gem side if that sounds like something we'd like to see

**Comment by jordancalhoun** [comment]
PR #6 adds the latest version of the Lucide icons.

**Comment by eelcoj** [comment]
> @eelcoj are you open to the idea of moving the syncing function of the rails_icon gem to pull the files directly from their repo or is there a specific reason you decided to move them into this vault repo? I can implement the change on the gem side if that sounds like something we'd like to see

This would be a much better long-term solution, with way less overhead! The solution with the vault always was a temporary solution. But I haven't looked into the details and how involved it is.

**Comment by jordancalhoun** [comment]
I'll create a branch and explore options, i think it would be relatively easy to do assuming the repo owners aren't changing the folder structure of where the icons reside often.

Ill submit it to this repo once its dialed in for you to look over when you get a chance!

**Comment by eelcoj** [comment]
Created this issue for it: https://github.com/Rails-Designer/rails_icons/issues/10
